const mockProducts = [
  {
    id: 1,
    nome: 'Furadeira de Impacto 750W',
    categoria: 'ferramentas',
    categoriaLabel: 'Ferramentas',
    descricao: 'Potencia e precisao para perfuracao em madeira, metal e concreto leve.',
    preco: 329.9,
    badge: 'Ferramenta eletrica',
    estoqueLabel: 'Disponivel para envio imediato',
    entrega: '3 a 6 dias uteis',
    visual: 'tool',
  },
  {
    id: 2,
    nome: 'Caixa Organizadora Profissional',
    categoria: 'ferragens',
    categoriaLabel: 'Ferragens',
    descricao: 'Estrutura resistente para transporte de ferramentas e acessorios.',
    preco: 189.5,
    badge: 'Organizacao',
    estoqueLabel: 'Pronta entrega',
    entrega: '2 a 5 dias uteis',
    visual: 'box',
  },
  {
    id: 3,
    nome: 'Kit Disjuntores e Trilho DIN',
    categoria: 'eletrica',
    categoriaLabel: 'Eletrica',
    descricao: 'Composicao ideal para quadros eletricos residenciais e comerciais.',
    preco: 214.9,
    badge: 'Eletrica',
    estoqueLabel: 'Estoque de giro continuo',
    entrega: '4 a 7 dias uteis',
    visual: 'electric',
  },
  {
    id: 4,
    nome: 'Conjunto de Registros e Conexoes',
    categoria: 'hidraulica',
    categoriaLabel: 'Hidraulica',
    descricao: 'Pecas para instalacoes hidraulicas com vedacao segura e acabamento limpo.',
    preco: 142.75,
    badge: 'Hidraulica',
    estoqueLabel: 'Disponivel em lote promocional',
    entrega: '3 a 5 dias uteis',
    visual: 'water',
  },
  {
    id: 5,
    nome: 'Painel Solar Monocristalino 550W',
    categoria: 'energia-solar',
    categoriaLabel: 'Energia solar',
    descricao: 'Alta eficiencia energetica para projetos residenciais e comerciais.',
    preco: 1249,
    badge: 'Energia solar',
    estoqueLabel: 'Sob consulta para grandes projetos',
    entrega: '5 a 10 dias uteis',
    visual: 'solar',
  },
  {
    id: 6,
    nome: 'Parafusadeira Bateria 20V',
    categoria: 'ferramentas',
    categoriaLabel: 'Ferramentas',
    descricao: 'Autonomia, ergonomia e torque para montagens e manutencao diaria.',
    preco: 419.9,
    badge: 'Mais vendida',
    estoqueLabel: 'Ultimas unidades do lote',
    entrega: '2 a 4 dias uteis',
    visual: 'driver',
  },
];

export async function getProducts() {
  return Promise.resolve(mockProducts);
}
