const mockProducts = [
  {
    id: 1,
    nome: 'Furadeira de Impacto 750W',
    categoria: 'ferramentas',
    categoriaLabel: 'Ferramentas',
    descricao: 'Potencia e precisao para perfuracao em madeira, metal e concreto leve.',
    preco: 329.9,
    badge: 'Ferramenta eletrica',
    estoqueLabel: 'Disponivel para envio imediato',
    entrega: '3 a 6 dias uteis',
    visual: 'tool',
    curatedHighlights: [
      { icon: 'bi-lightning-charge', label: '750W de potencia' },
      { icon: 'bi-bullseye', label: 'Alta precisao' },
      { icon: 'bi-shield-check', label: 'Uso profissional' },
    ],
  },
  {
    id: 2,
    nome: 'Caixa Organizadora Profissional',
    categoria: 'ferragens',
    categoriaLabel: 'Ferragens',
    descricao: 'Estrutura resistente para transporte de ferramentas e acessorios.',
    preco: 189.5,
    badge: 'Organizacao',
    estoqueLabel: 'Pronta entrega',
    entrega: '2 a 5 dias uteis',
    visual: 'box',
    curatedHighlights: [
      { icon: 'bi-box-seam', label: 'Material resistente' },
      { icon: 'bi-lock', label: 'Travas de seguranca' },
      { icon: 'bi-grid-3x3-gap', label: 'Divisorias internas' },
    ],
  },
  {
    id: 3,
    nome: 'Kit Disjuntores e Trilho DIN',
    categoria: 'eletrica',
    categoriaLabel: 'Eletrica',
    descricao: 'Composicao ideal para quadros eletricos residenciais e comerciais.',
    preco: 214.9,
    badge: 'Eletrica',
    estoqueLabel: 'Estoque de giro continuo',
    entrega: '4 a 7 dias uteis',
    visual: 'electric',
    curatedHighlights: [
      { icon: 'bi-shield-check', label: 'Seguranca certificada' },
      { icon: 'bi-tools', label: 'Facil instalacao' },
      { icon: 'bi-check2-circle', label: 'Alta durabilidade' },
    ],
  },
  {
    id: 4,
    nome: 'Conjunto de Registros e Conexoes',
    categoria: 'hidraulica',
    categoriaLabel: 'Hidraulica',
    descricao: 'Pecas para instalacoes hidraulicas com vedacao segura e acabamento limpo.',
    preco: 142.75,
    badge: 'Hidraulica',
    estoqueLabel: 'Disponivel em lote promocional',
    entrega: '3 a 5 dias uteis',
    visual: 'water',
    curatedHighlights: [
      { icon: 'bi-droplet', label: 'Vedacao confiavel' },
      { icon: 'bi-gear', label: 'Montagem pratica' },
      { icon: 'bi-award', label: 'Acabamento limpo' },
    ],
  },
  {
    id: 5,
    nome: 'Painel Solar Monocristalino 550W',
    categoria: 'energia-solar',
    categoriaLabel: 'Energia solar',
    descricao: 'Alta eficiencia energetica para projetos residenciais e comerciais.',
    preco: 1249,
    badge: 'Energia solar',
    estoqueLabel: 'Sob consulta para grandes projetos',
    entrega: '5 a 10 dias uteis',
    visual: 'solar',
    curatedHighlights: [
      { icon: 'bi-sun', label: 'Alta eficiencia' },
      { icon: 'bi-graph-up-arrow', label: 'Maior geracao' },
      { icon: 'bi-house-check', label: 'Uso residencial e comercial' },
    ],
  },
  {
    id: 6,
    nome: 'Parafusadeira Bateria 20V',
    categoria: 'ferramentas',
    categoriaLabel: 'Ferramentas',
    descricao: 'Autonomia, ergonomia e torque para montagens e manutencao diaria.',
    preco: 419.9,
    badge: 'Mais vendida',
    estoqueLabel: 'Ultimas unidades do lote',
    entrega: '2 a 4 dias uteis',
    visual: 'driver',
    curatedHighlights: [
      { icon: 'bi-battery-charging', label: 'Autonomia de 20V' },
      { icon: 'bi-hand-thumbs-up', label: 'Pegada ergonomica' },
      { icon: 'bi-wrench-adjustable-circle', label: 'Torque ajustavel' },
    ],
  },
  {
    id: 7,
    nome: 'Lampada LED Bulbo 12W 6500K',
    categoria: 'eletrica',
    categoriaLabel: 'Eletrica',
    descricao: 'Mais economia e iluminacao uniforme para ambientes residenciais e comerciais.',
    preco: 12.9,
    badge: 'Iluminacao',
    estoqueLabel: 'Disponivel para pronta entrega',
    entrega: '2 a 5 dias uteis',
    visual: 'bulb',
    curatedHighlights: [
      { icon: 'bi-lightbulb', label: 'Luz branca 6500K' },
      { icon: 'bi-piggy-bank', label: 'Baixo consumo' },
      { icon: 'bi-stars', label: 'Maior vida util' },
    ],
  },
  {
    id: 8,
    nome: "Joelho 90° Soldavel 25mm",
    categoria: 'hidraulica',
    categoriaLabel: 'Hidraulica',
    descricao: 'Conexao de alta qualidade para instalacoes hidraulicas com encaixe preciso.',
    preco: 12.9,
    badge: 'Conexao',
    estoqueLabel: 'Estoque local disponivel',
    entrega: '3 a 5 dias uteis',
    visual: 'pipe',
    curatedHighlights: [
      { icon: 'bi-droplet-half', label: 'Encaixe preciso' },
      { icon: 'bi-shield-check', label: 'Alta resistencia' },
      { icon: 'bi-tools', label: 'Aplicacao rapida' },
    ],
  },
  {
    id: 9,
    nome: 'Dobradiça Zincada 3" 3 Peças',
    categoria: 'ferragens',
    categoriaLabel: 'Ferragens',
    descricao: 'Ideal para portas e moveis com excelente acabamento e resistencia.',
    preco: 14.9,
    badge: 'Acabamento',
    estoqueLabel: 'Disponivel para envio imediato',
    entrega: '2 a 4 dias uteis',
    visual: 'hinge',
    curatedHighlights: [
      { icon: 'bi-gear', label: 'Abertura suave' },
      { icon: 'bi-brilliance', label: 'Acabamento zincado' },
      { icon: 'bi-check2-square', label: 'Fixacao segura' },
    ],
  },
  {
    id: 10,
    nome: 'Inversor On Grid 2kW',
    categoria: 'energia-solar',
    categoriaLabel: 'Energia solar',
    descricao: 'Desempenho e seguranca para instalacoes fotovoltaicas de pequeno e medio porte.',
    preco: 1699,
    badge: 'Inversor',
    estoqueLabel: 'Sob consulta para projeto',
    entrega: '5 a 9 dias uteis',
    visual: 'inverter',
    curatedHighlights: [
      { icon: 'bi-cpu', label: 'Monitoramento inteligente' },
      { icon: 'bi-shield-lock', label: 'Protecao eletrica' },
      { icon: 'bi-plug', label: 'Integra com sistema on-grid' },
    ],
  },
];

export async function getProducts() {
  return Promise.resolve(mockProducts);
}
